apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/kcp_openshift?ref=d985fb45581511141b4e1ed71ec251f522652e58

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: d985fb45581511141b4e1ed71ec251f522652e58
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: sha-8a7b2649611a0421fe9b29bcfbfdbdac4ba82bef

namespace: spi-system

patchesStrategicMerge:
  - delete-shared-configuration-file.yaml
